Traceback (most recent call last):
  File "/faststorage/project/EcoGenetics/general_workflows/population_genetics/fst_pi/configurations/collembola/Entomobrya_nicoleti/conservation_agriculture/../../../../workflow_source/scripts/update_collection_file.py", line 56, in update_matrix
    df = pd.read_csv(matrix_file, sep='\t', index_col=0)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anneaa/miniconda3/envs/ecogen_neutral_diversity_wf/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anneaa/miniconda3/envs/ecogen_neutral_diversity_wf/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anneaa/miniconda3/envs/ecogen_neutral_diversity_wf/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anneaa/miniconda3/envs/ecogen_neutral_diversity_wf/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anneaa/miniconda3/envs/ecogen_neutral_diversity_wf/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/faststorage/project/EcoGenetics/general_workflows/population_genetics/fst_pi/configurations/collembola/Entomobrya_nicoleti/conservation_agriculture/../../../../workflow_source/scripts/update_collection_file.py", line 89, in <module>
    update_matrix(input_file, matrix_file, species, output_file, prefix)
  File "/faststorage/project/EcoGenetics/general_workflows/population_genetics/fst_pi/configurations/collembola/Entomobrya_nicoleti/conservation_agriculture/../../../../workflow_source/scripts/update_collection_file.py", line 57, in update_matrix
    except (FileNotFoundError, EmptyDataError):
                               ^^^^^^^^^^^^^^
NameError: name 'EmptyDataError' is not defined

